resources:
  - name: txservice_src
    type: git
    check_every: 3m
    source:
      branch: main
      uri: git@github.com:eloqdata/tx_service.git
      private_key: ((git-key))

  - name: redis_src
    type: git
    check_every: 3m
    source:
      branch: main
      uri: git@github.com:eloqdata/eloqkv.git
      private_key: ((git-key))

  - name: eloq_test_src
    type: git
    check_every: 3m
    source:
      branch: main
      uri: git@github.com:eloqdata/eloq-test.git
      private_key: ((git-key))

  - name: eloq_metrics_src
    type: git
    check_every: 3m
    source:
      branch: main
      uri: git@github.com:eloqdata/eloq-metrics.git
      private_key: ((git-key))

  - name: eloq_ubuntu_2404
    type: registry-image
    source:
      repository: eloqdata/monograph-dev-ci-ubuntu2404
      tag: latest

jobs:
  - name: compile-test
    build_log_retention:
      builds: 500
    serial: true
    plan:
      - in_parallel:
          steps:
            - get: eloq_metrics_src
              trigger: true
            - get: txservice_src
              trigger: true
            - get: redis_src
              trigger: true
            - get: eloq_test_src
              trigger: true
            - get: eloq_ubuntu_2404
      - task: compile-test-task
        image: eloq_ubuntu_2404
        file: redis_src/concourse/tasks/main.yml
        vars:
          minio-access-key: ((minio-access-key))
          minio-endpoint: ((minio-endpoint))
          minio-secret-key: ((minio-secret-key))
        privileged: true
