resources:
  - name: redis_src
    type: git
    check_every: 3m
    source:
      branch: main
      uri: git@github.com:eloqdata/eloqkv.git
      private_key: ((git-key))

  - name: logservice_src
    type: git
    check_every: 3m
    source:
      branch: main
      uri: git@github.com:eloqdata/eloq_log_service.git
      private_key: ((git-key))

  - name: eloq_test_src
    type: git
    check_every: 3m
    source:
      branch: main
      uri: git@github.com:eloqdata/eloq-test.git
      private_key: ((git-key))

  - name: raft_host_manager_src
    type: git
    check_every: 3m
    source:
      branch: main
      uri: git@github.com:eloqdata/raft_host_manager.git
      private_key: ((git-key))

  - name: eloq_ubuntu_2404
    type: registry-image
    source:
      repository: eloqdata/eloq-build-ubuntu2404
      tag: latest
      username: eloqdata
      password: ((docker-secret-key))

jobs:
  - name: compile-test
    build_log_retention:
      builds: 500
    serial: true
    plan:
      - in_parallel:
          steps:
            - get: redis_src
              trigger: true
            - get: logservice_src
              trigger: true
            - get: raft_host_manager_src
              trigger: true
            - get: eloq_test_src
              trigger: true
            - get: eloq_ubuntu_2404
      - task: compile-test-task
        image: eloq_ubuntu_2404
        file: redis_src/concourse/tasks/main.ent.yml
        vars:
          cass-host: ((cassandra-host))
          minio-access-key: ((minio-access-key))
          minio-endpoint: ((minio-endpoint))
          minio-secret-key: ((minio-secret-key))
        privileged: true
