platform: linux
image_resource:
  type: registry-image
inputs:
  - name: logservice_src
  - name: eloqkv_pr
  - name: eloq_test_src
  - name: raft_host_manager_src
run:
  path: eloqkv_pr/concourse/scripts/pr.ent.bash
  args: ["((cass-host))", "((minio-endpoint))", "((minio-access-key))", "((minio-secret-key))"] 
