name: test-clang-format

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.18
      with:
        source: '.'
        exclude: './third_party ./external ./redis ./include/redis ./lua ./fpconv'
        extensions: 'h,cpp'
        clangFormatVersion: 18
        style: file
