name: Builder Docker

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "scripts/docker/builder.docker"
      - ".github/workflows/docker.builder.yml"
      - ".github/workflows/docker.template.yml"
      - "scripts/dep/**"
      - "scripts/install_dep*"
      - "data_substrate"
      - "data_substrate/.gitmodules"
      - "data_substrate/third_party/**"
      - "data_substrate/scripts/third_party/**"

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  builder:
    uses: ./.github/workflows/docker.template.yml
    with:
      dockerfile: ./scripts/docker/builder.docker
      image-name: eloqkv-builder
      force-latest: true
      latest-only: true
      checkout-submodules: "false"
      checkout-command: |
        git submodule update --init data_substrate
        git -C data_substrate submodule update --init --recursive third_party/src
    secrets: inherit
